### ISSUE TITLE
Memu Trouble on account

### ISSUE THREAD

**Issue by AkagiShiroe** [wDCat/ANRC#91] opened 2017-06-29 11:42 UTC
hmm @wDCat could you check memu? its seem have trouble loading savefiles from what im reading in reddit forum and now i got message everytime i login in title screen (written like this:コユ メッサゲ ガ　ゲット ニ シマッタ ：
予期しなし丶工ラーヵ遭発ま生せ聴ため、 処珪菫ヵ〟続行でき 工ラーコー ド: 99-1498730644 (random number in here)... could you investigate?.. probably do some patch on it.. or make some method? ._.
its "fate" game..

**Comment by Teodor19** [comment] 2017-06-29 11:55
I tried changing permissions of fate folder to default, but either i failed or it didn't work.
Just a note.

Also, entering in new acc is possible for the first time even though error 99 shows up.

**Comment by AkagiShiroe** [comment] 2017-06-29 11:56
i tried to decompiled it with some hex program called "Active Disk Editor" and it is got blocked.. that Execute Permission is set to "0".. only Read/Write allowed and seems MEmu does execute the file rather to read-it

**Comment by AkagiShiroe** [comment] 2017-06-29 11:59
![untitled](https://user-images.githubusercontent.com/14356240/27686426-a8b73076-5d0d-11e7-992c-f18759ea4d64.jpg)
and it does f*ck up some phone as well.. i hope DW fix it.. or we gonna do some patching on that execute permission. 
(F*O Seems resetting them into 0 to make it hidden for unroot devices, bad method i should say)

**Comment by reihunter360** [comment] 2017-06-29 12:35
Yeah. It does look like its an error on the APK's side. What the hell dw.

Currently though, i'm checking if a fresh install will also do the same shit.

LinuxMint+.VMDK Combo is nice to check the files out.

**Comment by reihunter360** [comment] 2017-06-29 13:09
Alright, so its impossible to play with Memu currently.

I've checked and tried with a fresh installation, but unfortunately, it didn't work.

I've already did the chmod 770 for the entire folder, so nothing's happening.

**Comment by AkagiShiroe** [comment] 2017-06-29 13:14
you could tried to modify it to have a "special permission" to change permission?... its should be on FGO Startup code where they change every "Execute" to 0 and only enable R/W for MasterCache.

**Comment by reihunter360** [comment] 2017-06-29 13:15
So specific chmods huh. I'll wait if DW fixes it, otherwise i'll work on it overnight.

**Comment by 29988122** [comment] 2017-06-29 14:02
Although I understand nothing you guys said, I still looking forward to the results!

Thank you all!

**Comment by reihunter360** [comment] 2017-06-29 20:50
@AkagiShiroe 
Alright so i've been poking around with the savedata files and MasterCache,

I've pretty much did a full chmod 770 and 700 (Owner Full Access, Everyone else gets nothing) to MasterCache and as well as the .dat files

From what I've read, it seems to be MeMu unable to read the files in that operation + the APK being a jerk to permissions (Can it even change permissions? I mean there's no root mode at all)

**Comment by wDCat** [comment] 2017-06-30 03:39
Maybe it detect vpn...

**Comment by AkagiShiroe** [comment] 2017-06-30 04:09
@reihunter360 it could from what i see.. every single apk check/apk got startup.. its allways change the permission for MasterCache to default DRW(Read/Write without execute which mean hidden them in the devices) im also trying to change User and Group to another but no luck.. apk still got them like a cake. no from what i see its only Check Permission -> Change (with method Read/Write for new one and if there's an exist one it will make another file from existing file from RAM), its probably hooked up with Root-Checker(that grub checking method.. hell i hate that.. probably that will be a hint for You @wDCat ). also you can read fgo log in data that named with random name with "App" name. I hope its just a bug for game reading method(map section.. if you tried to use bind you could login but you can't do anything except checking your servant & C.E List and my room. yeah terrible day for a terrible bug i say.

**Comment by cubanodun** [comment] 2017-06-30 04:59
@wDCat i dont think vpn has something to do, i know people that are playing from devices from Mexico and Peru and they are running the game fine i also saw people from japan complaining to the official twitter account about how the error was appearing even in iPhones

**Comment by reihunter360** [comment] 2017-06-30 09:25
DW put out a Dont Worry Post. Now we wait until they fuck things up again.

**Comment by AkagiShiroe** [comment] 2017-06-30 09:44
please no stupid emulator block again.. this things are f*cking unroot.. same as RemixOS

**Comment by reihunter360** [comment] 2017-06-30 15:44
Alright. looks like they've got a new protection of sorts.

The game may have sent out a login error to the servers, and then IP blocks you. Not sure for how long though.

Can't get into the login screen without encountering a generic "Cannot connect, retry!' Screen. On both accounts too.

The fuck DW. You're getting seriously bad each time.

Well anyways, that's just me, not sure who else is affected.

**Comment by Teodor19** [comment] 2017-06-30 15:51
The only difference here is that 99-14987 changed to 99-14988 on login attempt.
Just a note, every affected android phone i saw so far seems to be 5.1 Android, same as Cat's backup Memu. That doesn't explain iOS thing at all though.

**Comment by cubanodun** [comment] 2017-06-30 18:02
This is almost as bad as when they decided to ban random people for no reason at all back in the day (iirc was during the Kara no kyoukai event)

**Comment by AkagiShiroe** [comment] 2017-06-30 18:02
hi @wDCat any news on 4.x version?.. probably those version can run game very well to clarify/verify @Teodor19 mention that only 5.1 android got the problem.

**Comment by reihunter360** [comment] 2017-07-01 05:54
com.aniplex.fategrandorder ; [FOLDER]
U: Create and delete files
G: Access Files
O: no list, no create/delete access
x : Yes.
drwxr-x--x

/files/ /cache/ /app_SmartBeat/ /shared_prefs/
U: Create and delete files
G: Create and delete files
O: no list, no create/delete, access
X : Yes.
drwxrwx--x

Randomly Named Folders; /databases/
U: Create and delete files
G: None
O: None
X: Owner only.
drwx------
chmod 700

/file/MasterDataCaches; Cookies; HTTPCache; AssetCaches [FOLDER]
U: Create and Delete Files
G: none
O: none
X: Owner only
chmod 700

All files under AssetCaches\Android\; .dat files [Files]
U: Read and Write
G: None
O: None
x : Nope
chmod 600

All files under /shared_pref/ & /databases/ [Files]
U : Read and Write
G : Read and Write
O : None
x : Nope

lib [Files]
U : Read & Write
G : Read & Write
O : Read & Write
x : Yes.
(chmod 777)

Freshly installed FateGO folder looks like this.

Seems like most have special permissions.

But there's one thing that's bothering me, every file has this "when was this changed?"

I wonder if you can set chmod to not display that.

**Comment by RinFallen** [comment] 2017-07-01 06:42
Does anyone here know how to move data FGO on Remix OS Dual Boot to Phone ?
My account is stuck on Remix OS and i can't login to the game to bind a new code :( 
Pls help me i very appreciate for help.

**Comment by Teodor19** [comment] 2017-07-01 07:23
@RinFallen Answered on reddit.
Either i got lucky or Memu got fixed.

**Comment by RinFallen** [comment] 2017-07-01 07:33
What :O Memu can play for now ?

**Comment by RinFallen** [comment] 2017-07-01 08:28
@Teodor19  Let me ask 1 more thing, How can i move file FGO on Remix OS Dual Boot to HDD PC ?

**Comment by RinFallen** [comment] 2017-07-01 08:46
@Teodor19 I can mount file data.img on folder RMOS but i can't access and it forced me to format the disk 😀 and there is no data :v
![image](https://user-images.githubusercontent.com/26488875/27760541-2570e030-5e85-11e7-8791-9cc7bf116411.png)

**Comment by reihunter360** [comment] 2017-07-01 10:33
@RinFallen 
Uhm. You can mount the .img into virtualbox, and run something like Linux Mint VM (Installed w/ Shared Folders)

Then you can copy everything. .-.

**Comment by RinFallen** [comment] 2017-07-01 10:44
@reihunter360 Oh okay i'll try it :D Tks you bro.

**Comment by wDCat** [comment] 2017-07-01 12:08
@AkagiShiroe I have made a memu 4.4 image,but sadly,same problem...
you can download this image here: [Baidu Pan](https://pan.baidu.com/s/1nvFQF8H)(still updating,will be available after 1 hour)

For temporarily entering fgo:
1. switch on VPN (It's not able to connect to fgo server directly in China)
2. Open fgo and enter the "Touch Screen" screen
3. switch off VPN
4. return to fgo and touch screen.It will show "Connecting..." for a long time
5. wait for some second and switch on VPN
6. enjoy..

This way comes from another forum and works for many people.

**Comment by AkagiShiroe** [comment] 2017-07-01 12:24
@wDCat are those VPN method work for JP Server that come with error "99-XXXXX"?.. i want to bind my account.. (allready used it.. and got stuck.. urgh)

**Comment by wDCat** [comment] 2017-07-01 12:37
@AkagiShiroe  Yes,and It's need many tries.

**Comment by reihunter360** [comment] 2017-07-01 12:38
@wDCat 
thanks. I'll try your method.

**Comment by AkagiShiroe** [comment] 2017-07-01 12:38
... k, i have a lot of proxy here.. probably work.. u only said VPN Right?.. when i open FGO i use "Proxy 1" then i have to switch to "Proxy 2" when i click touch screen?.. then switch to "Proxy 1" Again?.. or Proxy 3?

**Comment by wDCat** [comment] 2017-07-01 12:47
@AkagiShiroe Almost.But "Proxy 2" should make fgo cannot connect to server (I guess,because I cannot connect to fgo server without a VPN)

**Comment by AkagiShiroe** [comment] 2017-07-01 12:51
there's no prompt "retry because disconect" right?

**Comment by wDCat** [comment] 2017-07-01 12:54
@AkagiShiroe yes

**Comment by AkagiShiroe** [comment] 2017-07-01 12:56
probably "1x.xx.xx" server?.. since fgo does have twin , normal one access "52.xx.xx.xx".. are you allready tried that method with memu?

**Comment by wDCat** [comment] 2017-07-01 13:06
@AkagiShiroe yes,I tried this method with Shadowsocks.
And I dont know which server it connects...

**Comment by reihunter360** [comment] 2017-07-01 13:25
@wDCat 

What VPN app are you using? and what settings?

**Comment by wDCat** [comment] 2017-07-01 13:34
@reihunter360 shadowsocks

**Comment by reihunter360** [comment] 2017-07-01 13:36
@wDCat 
any of the proxy should work right?

**Comment by RinFallen** [comment] 2017-07-01 14:00
So summary : First i need turn on VPN to connected to USA then Launch the game and then i turn off VPN waiting when the game appear "Connecting Failed" then i turn on VPN connecting to USA and Re-connect game ? Am i right ?

**Comment by AkagiShiroe** [comment] 2017-07-01 14:01
it is safe right?.. i hate if my account got banned.. got melt and shiki void here.. and lost my bind is the reckless mistake i ever made.

**Comment by RinFallen** [comment] 2017-07-01 14:03
@AkagiShiroe  Me too :( I can't login to the game to bind a new code :( If something happen with my account i'm gonna kill myself

**Comment by reihunter360** [comment] 2017-07-01 14:05
@AkagiShiroe @RinFallen Yeah i can't get the VPN slide to work. 

Guess i'll just wait for DW's Fix + wDcat's awesomeness

**Comment by RinFallen** [comment] 2017-07-01 14:08
@reihunter360  DW had replied a mail to my friend 
They said " We should wait for them fix 3 - 5 Days" lol

**Comment by AkagiShiroe** [comment] 2017-07-01 14:08
@wDCat this great cat never fall.. sorry to be honest i can't donate any money :( , i'll mirror your 4.4 Memu version soon and share it on group.. should i add some Shortlink that generate money for you? if you have any FB Contact could you add me? (for you too rei,rinfallen and teodore).. mine is "Akagi Shiroe".. with Rushella from Gin No Cross as profile picture.

**Comment by RinFallen** [comment] 2017-07-01 14:11
@AkagiShiroe  I can't add you :) Pls turn on Add friend button

**Comment by AkagiShiroe** [comment] 2017-07-01 14:12
@RinFallen really? here my [fb link](https://www.facebook.com/SE.RA.PH.404.Not.Found), i never disable friend button :(

**Comment by reihunter360** [comment] 2017-07-01 14:12
@AkagiShiroe sure.

**Comment by RinFallen** [comment] 2017-07-01 14:15
@AkagiShiroe "This page is not available" :<
Here's my [Facebook](https://www.facebook.com/thangvodung.info)

**Comment by AkagiShiroe** [comment] 2017-07-01 14:16
@RinFallen you should try right click the link then paste it.. github redirect is weird to be honest with..

**Comment by wDCat** [comment] 2017-07-01 14:25
A little donation link_(:зゝ∠)_:https://www.paypal.me/wdcatdonation

sorry that I don't use fb,but you can contact me by github and email:D

**Comment by AkagiShiroe** [comment] 2017-07-01 14:31
which email? @wDCat i never heard/read it before :lol.. do you hate fb? its the most used things before twitter and line or.. yeah whatever they call it now.

**Comment by AkagiShiroe** [comment] 2017-07-01 14:33
slow lmao speed.. i hate baidu when its come to speed and accessability
![untitled](https://user-images.githubusercontent.com/14356240/27762940-a7ef6286-5eb5-11e7-9042-6aff662df538.jpg)

**Comment by wDCat** [comment] 2017-07-01 14:44
my email: wdcat@foxmail.com
because of the holy shit firewall,only a few people around me can use fb....

**Comment by reihunter360** [comment] 2017-07-01 14:45
@wDCat chinese firewalls too thick? XD

**Comment by AkagiShiroe** [comment] 2017-07-01 14:48
@wDCat ever try Secured Server Hosting(ssh)? you could redirect most proxy and firewall to trick them they all accessing some number(server/proxy) instead the address\targeted host.

**Comment by wDCat** [comment] 2017-07-01 14:56
@AkagiShiroe It may be a good choice,I will try it:D

**Comment by AkagiShiroe** [comment] 2017-07-02 04:36
got my account back here (DW send bind code email).. any luck on it @wDCat  ?

**Comment by Orochi2018** [comment] 2017-07-02 12:34
I tried the 4.4 ova,thank you for making it,but for some reason i getting error 43,while it works for my friend(developer and usb debug are off ofc)Anyone know the reason why?How is this even possible?

**Comment by Teodor19** [comment] 2017-07-02 15:26
@Orochi2018 try note6 from [here](https://ff.reddit.com/r/grandorder/comments/6akkkq/emu_wars_episode_x_return_of_the_emu/), maybe it works for KitKat too.

@AkagiShiroe @reihunter360 I think i got it. Connected 4/5 times. (and fail was exactly on 00:00 JST, so it can be the case)
Can PM what i did, to test it on other systems. Not planning to publish it until 18:00 JST, want to see if DW fixes APK.

Also finally downloaded KitKat from baidu. Took 20 hours, woah.

**Comment by cubanodun** [comment] 2017-07-02 15:50
@Teodor19 i don't think they are going to fix it soon and if they are doing it they are going to prioritize iOS because that's the thing in japan, i have tried to download the 4.4 memu but no success, if you need someone to test it in memu from latin america send a message to see if it is a ip ban

**Comment by Teodor19** [comment] 2017-07-02 16:04
Couldn't find PM on github... [It's you?](https://www.reddit.com/user/Cubanodun)

**Comment by cubanodun** [comment] 2017-07-02 16:05
@Teodor19 yeah thats me

**Comment by Orochi2018** [comment] 2017-07-02 17:12
Error 60 now.Wow this game hates me like no other.Thanks for trying to help,atleast its a different error now,but no solution :(

**Comment by ScienceOfMemory** [comment] 2017-07-02 23:25
teodor19, if you're talking about the VPN method, people already tried that and it works for barely anyone. It's already posted in several reddit threads, too.

**Comment by mimikeneko** [comment] 2017-07-03 00:29
@orochi2018
Me too.
MEmu 2.9.6.1&MEmu Android 4.4 RC5&FGO 4.4 ova&error43.bat
get Error 60.

**Comment by Teodor19** [comment] 2017-07-03 01:41
@ScienceOfMemory Vаriation of VРN mеthod. Sо fаr wоrks fоr mе evеry timе. cubanodun mаnaged tо gеt it wоrking tоo, but with sоme prоblems аnd i dоn't knоw hоw repеatable it оn his еnd. Alsо аsked 4 mоre pеople tо tеst it.

**Comment by cubanodun** [comment] 2017-07-03 01:46
http://prntscr.com/fqw6p0 

i can confirm it works but when the server sync (aka when you get your daily gifts) it's going to kick you out, but you can connect again and keep playing normally 

We still don't know what the VPN trick has to do with permissions it's very weird indeed

**Comment by reihunter360** [comment] 2017-07-03 02:11
@Teodor19 vpn method again?

**Comment by Teodor19** [comment] 2017-07-03 02:15
Confirmed working for one more person.

And screenshot showing emus interface isn't a good idea. Though it may not be relevant anymore, as NA FGO launched. People from Aniplex USA totally can read this and report to DW.

@reihunter360 I don't know if that bypass thing is same as this baidu method though. Want to test it?

**Comment by reihunter360** [comment] 2017-07-03 02:19
@Teodor19 sure. why not.

**Comment by ScienceOfMemory** [comment] 2017-07-03 02:27
@Teodor19 I can easily guess your method then.
That has already been posted on reddit by some retard, by the way. Most people can't get in with the other VPN thing, which would only let you get to the main screen, so they're not gonna get in with this either since the only difference is crashing or not crashing when trying to spend AP. It's not really a fix but trying to sidestep the issue.
You get kicked out twice, at 0:00 and at 4:00, that's when server syncs happen. You can actually avoid this, but it's a bit of a hassle and requires knowing which connection requests trigger the sync call.
Also you occasionally get kicked out anyway because sometimes the server you are on is at capacity and you basically change which server you connect to, which re-runs the initial check and boots you. and that cannot be avoided because it is invisible. Most people don't realize that FGO runs over a server network and not one server. Each time your requests are shifted from one server to another you get booted. This happens on a by IP basis, not by client.
There are a few more issues associated with RAM usage and runtime, specifically regarding the initial login and caching issues from RAM which in some cases forces rebooting the emulator or the phone if you try this on a phone or an once working "fix" will stop working.
I also hope you realize that publicizing your "method" will just lead to it being unmade by DW post-haste server side. I.e. you post about this, it spreads, it finds some level of adoption. Boom. You can make it public and everyone using emus is screwed within a week, or you can keep it to yourself and the people you trust not to share it. All they have to do is re-run this check at every call request instead of just sync requests and the method goes BOOM.

**Comment by Teodor19** [comment] 2017-07-03 02:41
Not mine, i saw it on baidu, as i described it in my blog-like thingy.
Yeah, i understand, but what, should i just be only one to play on emu (manner of speech) until method goes boom anyway?
Edit: oh wait, i somehow missed your third sentence from the end, That doesn't seem fair or whatever right word would be.

**Comment by ScienceOfMemory** [comment] 2017-07-03 02:52
You figured it out yourself, nothing stops others from doing the same. 
The basic VPN method was put out there and didn't see any decent adoption rates, so there is no need for the devs to actually step in.
But if suddenly all those redditors posted all over social media how their VPN method works and what not, just like they post everywhere about playing on emulators, the devs will nuke things from orbit. And I know the mass redditor crowd cannot fucking help themselves. Publicizing it on 4chan would be just as bad if not worse by the way.
Share it with some people in private, pick them carefully, because I will do the same once it is evident this situation is not going away - so in a few days at most.
Because sharing it with everyone will just result in everyone losing it after anywhere between a day and a week. Because unlike before, they don't need an apk update to screw this one. They just need to place some more call requests in the server code and that can be done in 30 minutes, without maintenance.
Look at their history. They're incompetent when it comes to most things, especially running the game, but one thing they are very good at: screwing the emulator users. There is a reason perfare quit making unlocked apks.
You decide. Do you and those you trust want to keep playing until a separate way to fix this is found or DW actually does fix it themselves? Which I am not sure of they will. Or do you you want some cheap karma and then sit there, unable to play because you thought it was your job to spoonfeed all the people that can't even be bothered to read what's already posted.
This was added security. Some phones became collateral and they will most likely fix the phones but certainly not the emus.

**Comment by AkagiShiroe** [comment] 2017-07-03 09:19
@Teodor19 could you PM the method on my [FB?](https://www.facebook.com/SE.RA.PH.404.Not.Found) i want to roll those loli while it was rate-up.

**Comment by Teodor19** [comment] 2017-07-03 09:57
It's public already though. And this FB thingy says this person is not available or something.

**Comment by AkagiShiroe** [comment] 2017-07-03 09:58
@Teodor19 got published where?.. is that real?.. i never done anything with my fb account
(allready have this fb account around.. 5-7+ years)

**Comment by Teodor19** [comment] 2017-07-03 10:00
On reddit. Huh, try PM me then
_link deleted since i'm not using facebook and too lazy to check it_

**Comment by AkagiShiroe** [comment] 2017-07-03 10:02
@ScienceOfMemory you are definitely wrong.. i never see some method like that.. even on UDP Exchange method, the apk itself just can't read the data in some devices because every device have they're own build on the "android sdk" build, while trying VPN Method does forcing/accidently make the APK itself get bugged to access as they should in normal way. if you have proof on it then post here ._. im not that stupid enough to known it since i have a knowledge about it but i'd never learn reverse engineering.

**Comment by AkagiShiroe** [comment] 2017-07-03 10:36
k thx the method @Teodor19 found the way how to connect without yours.. its genuinely apk bug and doesn't have a complicated security... ive only have to block the connection half-way 2-4x then wait it flash blank white connecting.. voilla ( i can play)

**Comment by reihunter360** [comment] 2017-07-03 10:50
@AkagiShiroe your facebook has really bad errors.

**Comment by AkagiShiroe** [comment] 2017-07-03 10:52
@reihunter360 try post your fb link here.. i will send easy method to access fgo without 99-1 error.. no stupid android reboot or message pop-up anymore.

**Comment by reihunter360** [comment] 2017-07-03 10:53
facebook.com/rei.hunter @AkagiShiroe  here.

**Comment by AkagiShiroe** [comment] 2017-07-03 10:54
@reihunter360 done.. i allready add you and send message

**Comment by DarkWerWolf** [comment] 2017-07-03 11:58
@AkagiShiroe could i use your method to re-bind my account? as it stands it's stuck on the pre-EOR2 MEmu image and i keep getting the touch screen error

**Comment by ArbitraryFox** [comment] 2017-07-03 16:20
@AkagiShiroe Can you PM the method too? RemixOS not working for me shadowfaxspamprotection@gmail.com

**Comment by zetsuboushta** [comment] 2017-07-03 16:35
@AkagiShiroe 
can you pm the method to check it?
gorohov.alexei@gmail.com

**Comment by Teodor19** [comment] 2017-07-04 01:03
Or just check 'Play on PC' thread. _no one looks at sidebar ;__;_

**Comment by ArbitraryFox** [comment] 2017-07-04 01:20
@Teodor19 Then you might want to update your links. All of them.
Some of the solutions are outdated, like the Magisk/Xposed method which now fails.

And it's vague. How do you check what version of Play Services corresponds to your hardware? They will always auto-update to the latest version, you can't just download an apk and push it up hoping the version won't change

**Comment by AkagiShiroe** [comment] 2017-07-04 05:06
@ArbitraryFox my method doesn't consist any Google Play Update and confirm it was an APK-Side Bug since the objectives are "to halt/delay the game retrying to load the game files in another method/permission"
try send me a message or see the post on my [FB](https://www.facebook.com/SE.RA.PH.404.Not.Found) [Akagi Shiroe (Azuka)] i allready post video how to do it
@Teodor19 i feel that too.. in my group no one bother to check "pinpost" on how to play in PC.. instead they asking in the group/or commenting someone who post Screenshoot with Emu-bar

**Comment by DarkWerWolf** [comment] 2017-07-04 05:43
@AkagiShiroe i dont see anything on your facebook nor can i msg you there
@Teodor19 asked you on reddit how to make the data.img from remixos writable but no response so ima try it here
i managed to get the 4 account files from memu but idk how to mount data.img as writable
OSFMount doesnt let me, it just freezes and stops responding (ticking the Read-only drive option off)

**Comment by AkagiShiroe** [comment] 2017-07-04 07:02
@DarkWerWolf post your fb link here..

**Comment by DarkWerWolf** [comment] 2017-07-04 07:04
@AkagiShiroe 
https://www.facebook.com/profile.php?id=100018947265488

**Comment by zabakapro** [comment] 2017-07-04 10:41
@AkagiShiroe 
Please help me, too. My fb account: https://www.facebook.com/profile.php?id=100014011896814

**Comment by Abracadamos** [comment] 2017-07-04 11:49
@AkagiShiroe I tried updating Google Play Services and using a VPN and I'm still stuck on the title screen. I would really appreciate if you could help me.

My Facebook account if you need it: https://www.facebook.com/profile.php?id=100009871364625

**Comment by Smanro** [comment] 2017-07-04 12:07
@AkagiShiroe been trying vpn think all day long and still cant get it to work
pls help me with your method too sir. much appreciated https://www.facebook.com/anis.benjakard

**Comment by AkagiShiroe** [comment] 2017-07-04 12:13
@zabakapro @Abracadamos @Smanro @DarkWerWolf --" urgh.. know to extract account files? if yes send them.. i can bind it all for you. since i can easily log them on without anythings, or you could try contacting DW (Easier way).

**Comment by Abracadamos** [comment] 2017-07-04 12:40
@AkagiShiroe I'm playing on my phone and I have the bind code unused. I'm afraid to use it because I did it with a multiaccount app and that spare account that I used couldn't pass the title screen either.

**Comment by ArbitraryFox** [comment] 2017-07-04 15:36
@AkagiShiroe Why ask to add message or see your video when you set them all as private?
FB link: https://www.facebook.com/XCKDU

**Comment by TonyJaa212** [comment] 2017-07-04 16:03
@AkagiShiroe Can I get the method as well? Thanks!

https://www.facebook.com/profile.php?id=100018978884787

**Comment by MileniumJoestar** [comment] 2017-07-04 20:53
Does the method works for Remix OS or just memu?

**Comment by kjllmeplz** [comment] 2017-07-05 08:48
@AkagiShiroe Can i get the method ?
My FB : https://www.facebook.com/kjllmeplz

**Comment by Hyperversum** [comment] 2017-07-07 08:48
Somebody cares to like it to me too?

https://www.facebook.com/lorenzo.meulli

**Comment by AkagiShiroe** [comment] 2017-07-07 09:25
Note: they planning to improve database performance "and also fix it (i meant 99-1)".. expect something change in 18/7/2017... i hope nothing goes wrong for emu

**Comment by TonyJaa212** [comment] 2017-07-07 16:51
So we have to wait for 18 for the fix? dafuq DW lol.

**Comment by 29988122** [comment] 2017-07-12 16:56
I can confirm the issue solved after the latest update.
Phone and memu both got fixed on my side.

**Comment by AkagiShiroe** [comment] 2017-07-12 17:14
me too~ fixed here, its just an bug after all xD

**Closed as completed** 2017-07-19 09:34 UTC
